version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
  web:
    build: .
    command: ["bash", "-l", "-c", "python manage.py wait_for_db && python manage.py runserver 0:8000"]
    volumes:
      - .:/app/webapi
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    restart: unless-stopped
  redis:
    image: redis
  celery:
    restart: unless-stopped
    build:
      context: .
    command: ["bash", "-l", "-c", "celery -A cosapweb worker -l INFO"]
    volumes:
      - .:/app/webapi
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - web