version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
  web:
    build: .
    command: ["bash", "-l", "-c", "python manage.py runserver 0:8000"]
    volumes:
      - .:/app/webapi
    ports:
      - "8000:8000"
    environment:
      - COSAP_POSTGRES_NAME=postgres
      - COSAP_POSTGRES_USER=postgres
      - COSAP_POSTGRES_PASSWORD=postgres
      - COSAP_DJANGO_HOST=${COSAP_DJANGO_HOST}
      - COSAP_DJANGO_SECRET=${COSAP_DJANGO_SECRET:?}
      - COSAP_DJANGO_DEBUG=${COSAP_DJANGO_DEBUG}
    depends_on:
      - db
    restart: unless-stopped