version: "3.9"

services:
  cosap:
    image: itubioinformatics/cosap
    volumes:
      - ./data:/webapi/data/
      - ${COSAP_HG38_BUNDLE}:/cosap_data
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        "bash",
        "-l",
        "-c",
        "conda run --no-capture-output -n cosap celery -A cosap.celery.celery worker -l info -Q cosap_worker -c 3 -n cosap_worker@%h -Ofair",
      ]
    env_file:
      - .env
    working_dir: /
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${COSAP_POSTGRES_NAME}
      - POSTGRES_USER=${COSAP_POSTGRES_USER}
      - POSTGRES_PASSWORD=${COSAP_POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
  web:
    build: .
    command:
      [
        "bash",
        "-l",
        "-c",
        "python -u manage.py wait_for_db && python manage.py runserver 0:8000",
      ]
    volumes:
      - .:/webapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
